# theme = "kanagawa"
theme = "dracula"
# theme = "kanagawa-dragon"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "underline"

[editor.whitespace.render]
tab = "all"
