# theme = "kanagawa"
theme = "dracula"
# theme = "kanagawa-dragon"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "underline"

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1
